### ISSUE TITLE
Apple Watch Remote

### ISSUE THREAD

**Issue by salopeknet** [DeutscheMark/homebridge-kodi#28] opened 2022-02-19 00:18 UTC
Hello! Thank you for this great plugin!!

I was wondering, if you have already tested the original Apple Watch Remote App?
I can see the Kodi controls there, but nothing happens if I touch anything...

Controlling via the iOS Remote App (from Control Center) works fine!
So it should not be a big deal to add Apple Watch support for your plugin...

EDIT: I'm using homebridge-kodi 1.1.0-beta.1 with homebridge 1.4.0 on FHEM/RPi3B, iOS 15.3.1, watchOS 8.4.1

Thanks in advance,
 Micha

**Comment by DeutscheMark** [comment] 2022-04-19 11:51
Hi Micha,

it's a really good question why the Remote App is not working, but I see the same problem.

I think Homebridge has a problem there as there are no logs produced when tapping on the controls in the app. Other TV accessories are not working in there as well, e.g. "homebridge-harmony" and "homebridge-lg-webos-tv".

The problem is at least already reported (but not an active issue):
https://github.com/homebridge/homebridge/issues/3023

Will have to be patient there and hope the Homebridge team fixes it in the near future (if it's fixable).
I'm closing the issue until then, because there is nothing I can do about this right now it seems.

Thank you
DM

**Closed as completed by DeutscheMark** 2022-04-19 11:51 UTC
Labels: enhancement
